language: ruby
rvm:
  - 2.1.1
  - 2.2.2
env:
  - DB=sqlite
bundler_args: "--without development"
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate
  - RAILS_ENV=test bundle exec rake test
  - RAILS_ENV=test bundle exec rake spec
sudo: false
